name: Add Files Workflow

on:
  push:
    branches:
      - main

jobs:
  add_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Files
        run: |
          echo > file_1
          echo > file_2

      - name: Add Files to Git
        run: |
          git add file_1 file_2

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add file_1 and file_2"
